/**
 * Room walls: turning an absorption coefficient into PML damping.
 *
 * The reference has no materials at all — `Partition::absorption` is a scalar
 * that defaults to `0.8` and is never assigned from geometry (plan §1.5 item 3).
 * This is the piece that replaces it.
 *
 * ## The mapping
 *
 * A surface's octave-band absorption coefficient `α` fixes the normal-incidence
 * pressure reflection magnitude, `|R| = sqrt(1 − α)`, since α is an energy
 * ratio. What `|R|` a PML slab actually produces is not analytic — it depends on
 * the grading profile, the thickness, the Courant number and the discretization
 * — so it is **measured**: a 1D normal-incidence experiment sweeps the damping
 * and records the curve, and `dampingForAbsorption` inverts it.
 *
 * The plan called for that table to be generated by a script and checked in as
 * JSON. It is built at runtime and memoized instead. A checked-in table would
 * silently go stale the moment the stencil, the grading or the default Courant
 * number changed, and it cannot cover the `(thickness, grading, Courant)` grid
 * a caller might ask for. Expressing the damping dimensionlessly as
 * `σ̂ = σ·dx/c` makes one cached curve valid for every `dx` and `c`, so in
 * practice a run builds one curve and reuses it.
 *
 * ## What this can and cannot reach — measured, not assumed
 *
 * `|R|(σ̂)` is **not monotonic**. It falls from 1 as damping is introduced,
 * reaches a floor, then rises again: past the optimum the profile is steep
 * enough that the layer itself reflects. Above roughly `σ̂ ≈ 15` it goes
 * unstable outright. Only the falling branch is invertible, and that is the
 * branch used here.
 *
 * Measured floors at Courant 0.4, grading exponent 2:
 *
 * | thickness | min \|R\| | highest α reachable |
 * |-----------|-----------|---------------------|
 * | 10 cells  | 0.138     | 0.981               |
 * | 20 cells  | 0.030     | 0.9991              |
 * | 30 cells  | 0.010     | 0.9999              |
 * | 40 cells  | 0.011     | 0.9999              |
 * | 60 cells  | 0.005     | 1.0000              |
 *
 * (40 cells landing marginally above 30 is the geometric sampling ladder, not
 * physics; the floor is flat in that region.)
 *
 * Two consequences worth stating plainly. The plan's Phase 4 target of
 * `|R| < 1e-3` **is not met at any thickness tested** — a 20-cell layer floors
 * at 0.030 and even 60 cells only reaches 0.005. For terminating an open domain
 * that is a real limitation, and getting further would need a better-matched
 * profile than a graded `σ` sponge. For room surfaces it does not matter: real
 * materials sit below α = 0.95, comfortably inside what a 20-cell layer
 * reaches, and the round trip α → σ̂ → measured α is accurate to about 0.001
 * across α ∈ [0.05, 0.95]. `dampingForAbsorption` throws rather than silently
 * under-delivering if asked for more than the layer can produce.
 *
 * ## Limitations
 *
 * `createWall` refuses a time step the resulting slab cannot run at: a wall on
 * a 3D room face is a rank-3 PML and carries the 3D CFL limit, even though the
 * DCT interior it terminates has none. The calibration rig is 1D and cannot
 * detect that on its own.
 *
 * Normal incidence only, and frequency-independent — both intrinsic to the
 * method, not to this implementation. Angle-dependent absorption needs a
 * different boundary condition (a locally-reacting impedance surface, as in
 * Bilbao 2013, reference [6] in the plan), and per-band α needs one simulation
 * run per octave band, which is design decision D3.
 */

import { DctPartition } from './dct-partition';
import { Axis, spatialRank, vonNeumannCflLimit } from './partition';
import { PML_CFL_MARGIN, PmlPartition } from './pml-partition';
import { applyAllInterfaceForcing, findInterfaces } from './interface';

/** Normal-incidence pressure reflection magnitude for an absorption coefficient. */
export function reflectionMagnitude(alpha: number): number {
  if (!(alpha >= 0) || alpha > 1) {
    throw new Error(`Absorption coefficient must be in [0, 1], got ${alpha}`);
  }
  return Math.sqrt(1 - alpha);
}

/** The inverse: absorbed energy fraction for a pressure reflection magnitude. */
export function absorptionFromReflection(r: number): number {
  if (!(r >= 0) || r > 1) {
    throw new Error(`Reflection magnitude must be in [0, 1], got ${r}`);
  }
  return 1 - r * r;
}

export interface WallCalibration {
  /** PML thickness in cells. */
  thickness: number;
  /** Grading exponent of the sigma profile. */
  gradingExponent: number;
  /** Courant number `c·dt/dx` the layer will run at. */
  courant: number;
}

const DEFAULT_CALIBRATION: WallCalibration = {
  thickness: 20,
  gradingExponent: 2,
  courant: 0.4,
};

/**
 * Measure the normal-incidence reflection of a PML slab, in 1D.
 *
 * A pulse starts in the middle of a rigid-walled partition and splits. The
 * right-going half reaches the slab, partially reflects, and returns past a
 * probe; the left-going half reflects off the rigid wall and arrives much later.
 * The geometry below keeps those two arrivals separated, with room for the
 * round trip through the slab itself — a thick, weakly-damped slab echoes late,
 * and a window that closes too early reports it as perfectly absorbing.
 *
 * `sigmaHat` is the peak damping in units of `c/dx`, so the result depends only
 * on the shape of the problem and not on the grid scale.
 */
export function measureNormalIncidenceReflection(
  sigmaHat: number,
  calibration: WallCalibration = DEFAULT_CALIBRATION,
): number {
  const { thickness, gradingExponent, courant } = calibration;

  // Grid scale is arbitrary — the answer depends on sigmaHat and Courant only.
  const dx = 0.05;
  const c = 343;
  const dt = (courant * dx) / c;

  // Rig geometry. The domain is a power of two so the DCT takes the radix-2
  // path rather than Bluestein — the calibration is ~4x cheaper for it, and the
  // measurement does not care about the exact length. It must also be wide
  // enough that the slab echo clears before the rigid-wall echo arrives, which
  // needs n/4 > thickness.
  let n = 256;
  while (n < 8 * thickness) n *= 2;
  const source = n >> 1;
  const probe = n - (n >> 2);
  // Arrival times in steps: incident at (probe - source)/courant, the slab echo
  // at that plus 2*(n - probe)/courant plus the slab round trip 2*thickness/courant,
  // and the rigid-wall echo at (source + probe)/courant.
  const incidentAt = (probe - source) / courant;
  const wallEchoAt = (source + probe) / courant;
  // The slab echo cannot arrive before the round trip to the interface, and a
  // thick slab adds its own internal round trip on top.
  const slabEchoAt = incidentAt + (2 * (n - probe)) / courant;
  const slabRoundTrip = (2 * thickness) / courant;
  // Stop short of the rigid-wall echo: its leading edge arrives a little before
  // its peak, and letting it into the window reports the layer as worse than it
  // is — which truncates the calibration walk early.
  const windowEnd = wallEchoAt - 100;
  const steps = Math.ceil(windowEnd);

  const main = new DctPartition({
    box: { x: 0, y: 0, z: 0, w: n, h: 1, d: 1 },
    dx,
    c,
    dt,
  });
  const pml = new PmlPartition({
    box: { x: n, y: 0, z: 0, w: thickness, h: 1, d: 1 },
    dx,
    c,
    dt,
    axis: Axis.X,
    increasing: true,
    sigmaMax: (sigmaHat * c) / dx,
    gradingExponent,
  });

  const field = new Float64Array(n);
  for (let i = 0; i < n; i++) field[i] = Math.exp(-0.5 * ((i - source) / 4) ** 2);
  main.setPressure(field);

  const interfaces = findInterfaces([main, pml]);
  const trace = new Float64Array(steps);
  for (let s = 0; s < steps; s++) {
    applyAllInterfaceForcing(interfaces, c, dx);
    main.step();
    pml.step();
    trace[s] = main.pressure[probe];
  }

  const peak = (from: number, to: number) => {
    let worst = 0;
    const lo = Math.max(0, Math.floor(from));
    const hi = Math.min(steps, Math.ceil(to));
    for (let i = lo; i < hi; i++) worst = Math.max(worst, Math.abs(trace[i]));
    return worst;
  };

  const incident = peak(incidentAt - 60, incidentAt + 100);
  const reflected = peak(slabEchoAt - 40, Math.min(windowEnd, slabEchoAt + slabRoundTrip + 400));
  if (!(incident > 0) || !Number.isFinite(reflected)) return NaN;
  return reflected / incident;
}

export interface CalibrationCurve {
  calibration: WallCalibration;
  /** Damping samples in units of `c/dx`, ascending, on the falling branch. */
  sigmaHat: Float64Array;
  /** Measured reflection magnitude at each sample, descending. */
  reflection: Float64Array;
  /** Lowest reflection the layer can produce. */
  minReflection: number;
  /** Highest absorption coefficient the layer can realize. */
  maxAbsorption: number;
}

const curveCache = new Map<string, CalibrationCurve>();

function cacheKey(cal: WallCalibration): string {
  return `${cal.thickness}|${cal.gradingExponent}|${cal.courant}`;
}

/**
 * Build (and memoize) the falling branch of the `|R|(σ̂)` curve.
 *
 * Walks damping upward until the reflection stops improving, which is where the
 * branch ends. Roughly a dozen 1D runs, once per distinct calibration.
 */
export function calibrationCurve(
  calibration: WallCalibration = DEFAULT_CALIBRATION,
): CalibrationCurve {
  const key = cacheKey(calibration);
  const cached = curveCache.get(key);
  if (cached) return cached;

  // Sample the whole usable range first, then keep the falling branch. Breaking
  // on the first non-improving sample would stop at a noise wiggle far short of
  // the floor, which is exactly what an earlier version of this did.
  const sampledSigma: number[] = [0];
  const sampledR: number[] = [Math.min(1, measureNormalIncidenceReflection(0, calibration))];

  for (let sigmaHat = 0.004; sigmaHat <= 8; sigmaHat *= 1.3) {
    const r = measureNormalIncidenceReflection(sigmaHat, calibration);
    if (!Number.isFinite(r)) break; // the layer has gone unstable
    sampledSigma.push(sigmaHat);
    sampledR.push(r);
  }

  let argmin = 0;
  for (let i = 1; i < sampledR.length; i++) if (sampledR[i] < sampledR[argmin]) argmin = i;

  // Keep [0, argmin], dropping any sample that does not strictly improve, so the
  // result is invertible by interpolation.
  const sigmaHats: number[] = [sampledSigma[0]];
  const reflections: number[] = [sampledR[0]];
  for (let i = 1; i <= argmin; i++) {
    if (sampledR[i] < reflections[reflections.length - 1]) {
      sigmaHats.push(sampledSigma[i]);
      reflections.push(sampledR[i]);
    }
  }

  const curve: CalibrationCurve = {
    calibration,
    sigmaHat: Float64Array.from(sigmaHats),
    reflection: Float64Array.from(reflections),
    minReflection: reflections[reflections.length - 1],
    maxAbsorption: absorptionFromReflection(
      Math.min(1, reflections[reflections.length - 1]),
    ),
  };
  curveCache.set(key, curve);
  return curve;
}

/** Discard memoized curves. Only useful in tests. */
export function clearCalibrationCache(): void {
  curveCache.clear();
}

/**
 * Damping (in units of `c/dx`) that produces a target reflection magnitude.
 *
 * Interpolates the falling branch linearly in `σ̂` against `log|R|`, which is
 * where the curve is closest to straight. Throws if the target is below what
 * the layer can reach — a silent clamp would hand back a wall quietly more
 * reflective than the material it is standing in for.
 */
export function dampingForReflection(
  targetR: number,
  calibration: WallCalibration = DEFAULT_CALIBRATION,
): number {
  if (!(targetR >= 0) || targetR > 1) {
    throw new Error(`Reflection magnitude must be in [0, 1], got ${targetR}`);
  }
  const curve = calibrationCurve(calibration);
  const { sigmaHat, reflection } = curve;

  if (targetR >= reflection[0]) return 0;
  if (targetR < curve.minReflection) {
    throw new Error(
      `A ${calibration.thickness}-cell PML at grading ${calibration.gradingExponent} ` +
        `reaches |R| = ${curve.minReflection.toFixed(4)} at best (alpha <= ` +
        `${curve.maxAbsorption.toFixed(4)}); ${targetR.toFixed(4)} was requested. ` +
        `Use a thicker layer.`,
    );
  }

  for (let i = 1; i < reflection.length; i++) {
    if (targetR >= reflection[i]) {
      const loR = Math.log(Math.max(reflection[i - 1], 1e-12));
      const hiR = Math.log(Math.max(reflection[i], 1e-12));
      const t = (Math.log(targetR) - loR) / (hiR - loR);
      return sigmaHat[i - 1] + t * (sigmaHat[i] - sigmaHat[i - 1]);
    }
  }
  return sigmaHat[sigmaHat.length - 1];
}

/** Damping (in units of `c/dx`) that realizes an absorption coefficient. */
export function dampingForAbsorption(
  alpha: number,
  calibration: WallCalibration = DEFAULT_CALIBRATION,
): number {
  return dampingForReflection(reflectionMagnitude(alpha), calibration);
}

/**
 * Build a PML slab that terminates one face of a partition box with a surface of
 * the given absorption coefficient.
 */
export function createWall(options: {
  /** The box being terminated, in global cell coordinates. */
  box: { x: number; y: number; z: number; w: number; h: number; d: number };
  axis: Axis;
  /** Which face — the box's high edge on `axis`, or its low edge. */
  high: boolean;
  alpha: number;
  dx: number;
  c: number;
  dt: number;
  thickness?: number;
  gradingExponent?: number;
}): PmlPartition {
  const {
    box,
    axis,
    high,
    alpha,
    dx,
    c,
    dt,
    thickness = DEFAULT_CALIBRATION.thickness,
    gradingExponent = DEFAULT_CALIBRATION.gradingExponent,
  } = options;

  const courant = (c * dt) / dx;

  // Guard before calibrating. A room face keeps its transverse extents, so a
  // wall on a 3D room is a rank-3 slab and carries the 3D CFL limit (~0.47),
  // while the DCT interior it terminates has no limit at all. At the plan's
  // default Courant 0.5 the wall diverges and the room beside it looks fine.
  // The calibration rig is 1D — rank 1, limit ~0.81 — so it would happily build
  // and cache a curve for a dt the real slab cannot run at. Fail here, where
  // the geometry is known, rather than inside the constructor with no context.
  const slabRank = spatialRank(
    axis === Axis.X ? thickness : box.w,
    axis === Axis.Y ? thickness : box.h,
    axis === Axis.Z ? thickness : box.d,
  );
  const limit = PML_CFL_MARGIN * vonNeumannCflLimit(slabRank);
  if (courant > limit) {
    throw new Error(
      `A wall on this face is a rank-${slabRank} PML slab, limited to Courant ` +
        `${limit.toFixed(3)}, but dt gives ${courant.toFixed(3)}. The wall slab sets ` +
        `the time step for the whole simulation — DctPartition interiors have no CFL ` +
        `limit — so reduce dt rather than the layer thickness.`,
    );
  }

  const calibration: WallCalibration = { thickness, gradingExponent, courant };
  const sigmaHat = dampingForAbsorption(alpha, calibration);

  const origin: ['x', 'y', 'z'] = ['x', 'y', 'z'];
  const extent: ['w', 'h', 'd'] = ['w', 'h', 'd'];
  const slab = { ...box };
  slab[extent[axis]] = thickness;
  slab[origin[axis]] = high ? box[origin[axis]] + box[extent[axis]] : box[origin[axis]] - thickness;

  return new PmlPartition({
    box: slab,
    dx,
    c,
    dt,
    axis,
    // sigma must vanish at the face touching the room and peak at the outer
    // face, so the direction of growth flips with which side the slab is on.
    increasing: high,
    sigmaMax: (sigmaHat * c) / dx,
    gradingExponent,
  });
}
